# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: push-dogsbody.azurecr.io
    - task: Docker@2
      displayName: Docker login to GitHub container registry
      inputs:
        command: login
        containerRegistry: github.com_DogsbodyServices
    - task: Docker@2
      displayName: Build and push to ACR
      inputs:
        command: buildAndPush
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
#        containerRegistry: push-dogsbody.azurecr.io
        repository: vsftpd_container
        tags: latest
