# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: push-dogsbody.azurecr.io
    - task: Docker@2
      displayName: Docker login to GitHub container registry
      inputs:
        command: login
        containerRegistry: github-container-registry

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: vsftpd_container
        tags: |
          - latest
          - DogsbodyServices/vsftpd_container:latest


    - task: Docker@2
      displayName: Push to ACR
      inputs:
        command: push
        containerRegistry: push-dogsbody.azurecr.io
        repository: vsftpd_container
        tags: latest
    - task: Docker@2
      displayName: Push to GitHub container registry
      inputs:
        command: push
        containerRegistry: github-container-registry
        repository: vsftpd_container
        tags: latest
