# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- releases/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: push-dogsbody.azurecr.io

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: push-dogsbody.azurecr.io
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: vsftpd
        # set tag based on branch name
        tags: |
          latest
          $(Build.SourceBranchName)
