# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- release/*

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Docker login
      inputs:
        command: login
        containerRegistry: push-dogsbody.azurecr.io

    - task: Docker@2
      displayName: Build an image
      inputs:
        command: buildAndPush
        containerRegistry: push-dogsbody.azurecr.io
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        repository: vsftpd
        # set tag based on branch name
        tags: |
          latest
          $(Build.SourceBranchName)

#- stage: Generate SBOM with grype
#  displayName: Generate SBOM with grype
#  dependsOn: Build
#  jobs:
#  - job: GenerateSBOM
#    displayName: Generate SBOM
#    pool:
#      vmImage: ubuntu-latest
#    steps:
#    - script: |
#        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
#      displayName: Install grype
#    - script: |
#        grype vsftpd:latest -o cyclonedx-json > $(Build.ArtifactStagingDirectory)/sbom-vsftpd-latest.json
#        grype vsftpd:$(Build.SourceBranchName) -o cyclonedx-json > $(Build.ArtifactStagingDirectory)/sbom-vsftpd-$(Build.SourceBranchName).json
#      displayName: Generate SBOM
#    - 
