services:
  cw_ftp:
    #image: dogsbody.azurecr.io/vsftpd_container:latest
    image: ftp_container:latest
    container_name: ftp_container
    ports:
      - "21:21"
      - "2222:22"
      - "10000-10250:10000-10250"
    environment:
      PASV_MIN_PORT: "10000"
      PASV_MAX_PORT: "10250"
#      GCS_BUCKET_NAME: "your-gcs-bucket-name"
#      GCS_MOUNT_PATH: "/mnt/gcs"
    volumes:
      - /home/aaron.watson/ftp_container/config/users.json:/etc/vsftpd/users.json:ro