services:
  cw_ftp:
    image: dogsbody.azurecr.io/vsftpd_container:latest
    container_name: ftp_container
    ports:
      - "21:21"
      - "2222:22"
      - "10000-10250:10000-10250"
    environment:
      USER_CONFIG_PATH: "/etc/vsftpd/users.json"
      PASV_MIN_PORT: "10000"
      PASV_MAX_PORT: "10250"
    volumes:
      - ./config.user.json:/etc/vsftpd/users.json